'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { Proposal } from '../../../../lib/contracts';
import { apiClient } from '../../../../lib/api-client';
import { EmptyState, LoadingSpinner } from '../../../../components/ui';

export default function PlanningPage() {
  const params = useParams();
  const projectId = params?.id as string;

  const [taskProposals, setTaskProposals] = useState<Proposal[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    if (!projectId) return;
    apiClient
      .listProposals(projectId)
      .then((res) => {
        const tasks = (res.proposals || []).filter((p) => p.entityType === 'task');
        setTaskProposals(tasks);
      })
      .catch((err) => console.error(err))
      .finally(() => setIsLoading(false));
  }, [projectId]);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24, maxWidth: 1200, margin: '0 auto' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 16 }}>
        <div>
          <h1 style={{ fontSize: '1.5rem', fontWeight: 700, color: 'var(--text-primary)' }}>
            Implementation Plan & Engineering Tasks
          </h1>
          <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', marginTop: 4 }}>
            Actionable work breakdowns generated by the Planning Specialist and traced to requirements.
          </p>
        </div>

        <Link href={`/projects/${projectId}/chat`} className="btn btn-primary">
          💬 Plan in AI Chat
        </Link>
      </div>

      {isLoading ? (
        <LoadingSpinner size="lg" label="Loading tasks and work breakdown..." />
      ) : taskProposals.length === 0 ? (
        <EmptyState
          icon="✅"
          title="No Tasks Planned Yet"
          description="Ask the Planning Agent in Chat to generate an actionable implementation breakdown from your requirements."
          action={
            <Link href={`/projects/${projectId}/chat`} className="btn btn-primary">
              💬 Generate Task Breakdown
            </Link>
          }
        />
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
          {taskProposals.map((prop) => {
            const task = prop.entityPayload || {};
            return (
              <div key={prop.proposalId} className="card card-hover" style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <span className={`badge ${prop.status === 'approved' ? 'badge-approved' : 'badge-pending'}`}>
                      {prop.status}
                    </span>
                    <h3 style={{ fontSize: '1.0625rem', fontWeight: 600, color: 'var(--text-primary)' }}>
                      {task.title || 'Untitled Task'}
                    </h3>
                  </div>
                  <span className="badge badge-blue">{task.priority || 'MUST'}</span>
                </div>

                {task.description && (
                  <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', lineHeight: 1.5 }}>
                    {task.description}
                  </p>
                )}

                {task.requirementRefs && task.requirementRefs.length > 0 && (
                  <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                    Traces to Requirements: <code style={{ color: '#38bdf8' }}>{task.requirementRefs.join(', ')}</code>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
