'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { Proposal } from '../../../../lib/contracts';
import { apiClient } from '../../../../lib/api-client';
import { EmptyState, LoadingSpinner } from '../../../../components/ui';

export default function TestingPage() {
  const params = useParams();
  const projectId = params?.id as string;

  const [testProposals, setTestProposals] = useState<Proposal[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    if (!projectId) return;
    apiClient
      .listProposals(projectId)
      .then((res) => {
        const tests = (res.proposals || []).filter((p) => p.entityType === 'test' || p.entityType === 'testcase');
        setTestProposals(tests);
      })
      .catch((err) => console.error(err))
      .finally(() => setIsLoading(false));
  }, [projectId]);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24, maxWidth: 1200, margin: '0 auto' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 16 }}>
        <div>
          <h1 style={{ fontSize: '1.5rem', fontWeight: 700, color: 'var(--text-primary)' }}>
            Testing Strategies & QA Scenarios
          </h1>
          <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', marginTop: 4 }}>
            Test cases generated by the Testing Specialist validating acceptance criteria.
          </p>
        </div>

        <Link href={`/projects/${projectId}/chat`} className="btn btn-primary">
          💬 Generate Tests in Chat
        </Link>
      </div>

      {isLoading ? (
        <LoadingSpinner size="lg" label="Loading QA test cases..." />
      ) : testProposals.length === 0 ? (
        <EmptyState
          icon="🧪"
          title="No Test Cases Generated"
          description="Ask the Testing Specialist in Chat to generate unit, integration, and security test cases."
          action={
            <Link href={`/projects/${projectId}/chat`} className="btn btn-primary">
              💬 Generate Test Cases
            </Link>
          }
        />
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
          {testProposals.map((prop) => {
            const tc = prop.entityPayload || {};
            return (
              <div key={prop.proposalId} className="card card-hover" style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <span className={`badge ${prop.status === 'approved' ? 'badge-approved' : 'badge-pending'}`}>
                      {prop.status}
                    </span>
                    <span className="badge badge-purple">{tc.type || 'UNIT'}</span>
                    <h3 style={{ fontSize: '1.0625rem', fontWeight: 600, color: 'var(--text-primary)' }}>
                      {tc.title || 'Untitled Test Case'}
                    </h3>
                  </div>
                </div>

                {tc.procedure && tc.procedure.length > 0 && (
                  <div style={{ background: 'var(--bg-input)', padding: 12, borderRadius: 'var(--radius-md)', border: '1px solid var(--border-color)' }}>
                    <div style={{ fontSize: '0.8125rem', fontWeight: 600, color: 'var(--text-secondary)', marginBottom: 6 }}>
                      Execution Procedure:
                    </div>
                    <ol style={{ paddingLeft: 20, margin: 0, fontSize: '0.8125rem', color: 'var(--text-primary)' }}>
                      {tc.procedure.map((step: string, sIdx: number) => (
                        <li key={sIdx} style={{ marginBottom: 4 }}>{step}</li>
                      ))}
                    </ol>
                  </div>
                )}

                {tc.expectedResult && (
                  <div style={{ fontSize: '0.8125rem', color: '#34d399' }}>
                    <strong>Expected Result: </strong> {tc.expectedResult}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
